/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package swing;

import domainmodel.DienThoai;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Image;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.Border;
import repository.impl.DienThoaiRepository;
import util.ImageHelper;

/**
 *
 * @author sktfk
 */
public class Test extends javax.swing.JFrame {

    /**
     * Creates new form Test
     */
    DienThoaiRepository dienThoaiRepository = new DienThoaiRepository();

    public Test() {
        initComponents();
        addPanel();
        Test that;
        that = this;
    }

    void addPanel() {
        FlowLayout flowLayout = new FlowLayout();
        flowLayout.setAlignment(FlowLayout.LEFT);
        flowLayout.setHgap(10);
        flowLayout.setVgap(10);
        pnlTong.setLayout(flowLayout);
        DienThoai dienThoai = dienThoaiRepository.getAll1().get(0);
        try {
            Image img = ImageHelper.createFromByteArray(dienThoai.getAnh(), "png");
//            Image setImg = img.getScaledInstance(lblAnh.getWidth(), lblAnh.getHeight(), Image.SCALE_SMOOTH);
            for (int i = 0; i < 20; i++) {
                BorderLayout borderLayout = new BorderLayout();
                borderLayout.setVgap(4);
                JPanel panel = new JPanel();
                panel.setBackground(new java.awt.Color(255, 255, 255));
                panel.setSize(100, 100);
                panel.setLayout(borderLayout);
//                panel.setBackground(Color.red);
                JLabel label = new JLabel(new ImageIcon(ImageHelper.resige(img, 100, 70)));
                panel.add(label, BorderLayout.NORTH);
                JLabel ten = new JLabel("Iphone X");
                panel.add(ten);
                panel.add(ten, BorderLayout.CENTER);
                JLabel label1 = new JLabel("7000");
                label1.setForeground(Color.red);
                panel.add(label1, BorderLayout.SOUTH);
                panel.addMouseListener(new MouseListener() {
                    @Override
                    public void mouseClicked(MouseEvent e) {
                        JOptionPane.showMessageDialog(null, "Hello ");
                    }

                    @Override
                    public void mousePressed(MouseEvent e) {
                    }

                    @Override
                    public void mouseReleased(MouseEvent e) {
                    }

                    @Override
                    public void mouseEntered(MouseEvent e) {
                        panel.setBackground(new java.awt.Color(100, 149, 237));
                    }

                    @Override
                    public void mouseExited(MouseEvent e) {
                        panel.setBackground(new java.awt.Color(255, 255, 255));

                    }
                });
                pnlTong.add(panel);
            }
//            lblAnh.setIcon(new ImageIcon(ImageHelper.resige(img, lblAnh.getWidth(), lblAnh.getHeight())));

        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scpTong = new javax.swing.JScrollPane();
        pnlTong = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        scpTong.setPreferredSize(new java.awt.Dimension(400, 300));

        pnlTong.setBackground(new java.awt.Color(255, 255, 255));
        scpTong.setViewportView(pnlTong);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(scpTong, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scpTong, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Test().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlTong;
    private javax.swing.JScrollPane scpTong;
    // End of variables declaration//GEN-END:variables
}
